#set text(font: "Open Sans", size: 8pt)
#set heading(level: 1, text: set text(font: "Bebas Neue", size: 16pt, color: "#003366"))
#set heading(level: 2, text: set text(font: "Lato", size: 14pt, color: "#003366"))
#set page(background: "#f0f0f0")
#set align(center)